### ISSUE TITLE
Shouldn't indexAction() be mandatory in `AbstractController` class?

### ISSUE THREAD

**Issue by gabidj** [dotkernel/dot-controller#11]
In `Dot\Controller\AbstractActionController::dispatch()` the `index` action is the default action. If it doesn't exist next middleware will be called will generate a 404 error. 

`Dot\Controller\AbstractController::getMethodFromAction()` will return `indexAction` for no action given.

Wouldn't it be better to add the `indexAction()` method ?

 It helps the developer see his middleware was routed.

**Comment by n3vrax** [comment]
I get that when first using controllers and forgetting to define the indexAction, the 404 response might be a bit confusing, but a developer should be aware of what he's doing. We also recommend, in our documentation, to define this index action as a default one.

I'll say from start that the arguments to make this change or not are balanced. But I'm still slightly reserved regarding this change. Does it add real benefits?

Consider this
* the way indexAction is treated now, is like any other action. This falls better into the controller action convention
* the index action is not even required if the route is defined to have an action parameter which is required( e.g `/controller/{action}`)
* because controllers are middleware, they can be chained under the same route.  The actions are searched in the order middleware were added to the pipeline. If one action is not defined in the first one, it will go to the next middleware, which could be another controller, where the action might be defined. The indexAction being treated as a regular action, it will integrate better into this.

And let's not forget that Zend Expressive and DotKernel are for responsible developers that don't want to be restricted by so many rules as in the case of a full stack framework. The fewer, the better :)

To conclude, the strongest  argument I can give for leaving things as they are is that developers, being able to define their routes at will, they should be able to define the controller actions accordingly. 
The indexAction is more of a convention. If you know your route supports paths with an optional action parameter, you should define the index action, otherwise you won't need it.

We'll might reconsider this for next versions, but for now we'll keep structural changes to minimum and focus on bug fixing instead

Thanks!
Tibi
